version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=paftamiyap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=127.0.0.1
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  web:
    build: .
    restart: on-failure
    volumes:
      - .:/code
    command: bash -c "python manage.py makemigrations paftapp && python manage.py migrate && python manage.py loaddata paftapp/software_texture.json && python manage.py loaddata paftapp/mapsheet_texture.json && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db